pinterest/pin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length
from flask_wtf.file import FileField, FileAllowed


class PinCreation(FlaskForm):
    """Form for creating and updating Pin"""
    picture = FileField('Please upload image of your new pin',
                        validators=[FileAllowed(['jpg', 'png', 'jpeg', 'mp4', 'movie', 'gif'])])
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=20)])
    pin_content = StringField('Content', validators=[DataRequired(), Length(max=150)])
    is_private = BooleanField('Private Pin?')
    submit = SubmitField('Post')


class PinboardCreation(FlaskForm):
    """Form for creating a pin board"""
    pin_board_name = StringField('PinBoard Name', validators=[DataRequired(), Length(min=2, max=80)])
    board_is_private = BooleanField('Keep this board a secret')
    submit = SubmitField('Create')


class AddPinToPinboard(FlaskForm):
    submit = SubmitField('Add to pinboard?')


class FilteredPins(FlaskForm):
    submit = SubmitField('Go')


class Like(FlaskForm):
    submit = SubmitField('LIKE')


class CommentForm(FlaskForm):
    comment = StringField('Add comment', validators=[DataRequired()])
    submit = SubmitField('Post')

pinterest/admin/routes.py
from functools import wraps
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from pinterest.admin.forms import NewCategory
from flask_login import login_required, current_user
from pinterest import db
from pinterest.models import Category, User, Pins

admin = Blueprint('admin', __name__)


def admin_access(f):
    """ A decorator used for giving access only to admins for specific pages"""
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if current_user.is_admin:
            return f(*args, **kwargs)
        else:
            flash('Only Admin have rights to access this page', 'error')
            abort(403)

    return decorated_function


@admin.route("/adminhome")
@login_required
@admin_access
def home():
    """Admin Home Page"""
    return render_template('admin.html')


@admin.route("/category")
@login_required
@admin_access
def category():
    """Category Home Page"""
    return render_template('category.html')


@admin.route("/addcategory", methods=['GET', 'POST'])
@login_required
@admin_access
def add_category():
    """ For adding New Category """
    form = NewCategory()
    if form.validate_on_submit():
        category = Category(category_name=form.category_name.data)
        db.session.add(category)
        db.session.commit()
        flash("Category added successfully", category='success')
        return redirect(url_for('admin.category'))
    return render_template('new_category.html', form=form, legend='New Category')


@admin.route("/viewcategory", methods=['GET'])
@login_required
@admin_access
def view_category():
    """ Viewing Categories """
    categories = Category.query.order_by(Category.category_name.asc())
    return render_template('view_category.html', categories=categories)


@admin.route("/viewcategory/delete/<category_id>", methods=['GET', 'POST'])
@login_required
@admin_access
def delete_category(category_id):
    """ Deleting Categories """
    category = Category.query.get_or_404(category_id)
    pins = Pins.query.filter_by(category_id=category_id).all()
    if pins:
        flash("You cannot delete this category", category='danger')
        return redirect(url_for('admin.view_category'))
    else:
        db.session.delete(category)
        db.session.commit()
        flash('Category has been deleted', 'success')
        return redirect(url_for('admin.view_category'))


@admin.route("/viewcategory/update/<category_id>", methods=['GET', 'POST'])
@login_required
@admin_access
def update_category(category_id):
    """Updating existing categories """
    category = Category.query.get_or_404(category_id)
    form = NewCategory()
    if form.validate_on_submit():
        category.category_name = form.category_name.data
        db.session.commit()
        flash('Your Category has been updated', 'success')
        return redirect(url_for('admin.view_category'))
    elif request.method == 'GET':
        form.category_name.data = category.category_name  # for filling values
    return render_template('new_category.html', legend='Update Category', form=form)


@admin.route("/user_info", methods=['GET', 'POST'])
@login_required
@admin_access
def view_user_info():
    """Shows user info like email,username,and total pins created by respective user"""
    # pin=db.session.query(Pins.user_id, func.count(Pins.id)).group_by(Pins.user_id).all()
    users = User.query.all()
    return render_template('user_info.html', users=users)

pinterest/chat/__init__.py
from flask import Blueprint

chat = Blueprint('chat', __name__)

from . import routes, events

pinterest/chat/routes.py
from flask import render_template
from flask_login import current_user
import secrets
import string
from . import chat
from .. import db
from ..models import User, Room


@chat.route('/chat/<recipient>', methods=['GET', 'POST'])
def chat_func(recipient):
    """Chat room"""
    user = User.query.filter_by(username=recipient).first_or_404()
    room = Room.query.filter(Room.sender_id.in_([current_user.id, user.id]),
                             Room.recipient_id.in_([current_user.id, user.id])).first()
    if not room:
        res = ''.join(secrets.choice(string.ascii_uppercase + string.digits)
                      for i in range(10))
        room = Room(
            sender_id=current_user.id,
            recipient_id=user.id,
            room_name=res
        )
        db.session.add(room)
        db.session.commit()
    return render_template('chat.html', room=room.room_name, sender_id=current_user.id, recipient_id=user.id)

pinterest/pin/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from pinterest.pin.forms import PinCreation, PinboardCreation, AddPinToPinboard, FilteredPins,CommentForm
from flask_login import login_required, current_user
from pinterest import db
from pinterest.models import Pins, Category, User, Pinboard, SavePin, Board_of_Pins, Vote, Comments
#import cloudinary.uploader

from pinterest.pin.utils import save_picture

pin = Blueprint('pin', __name__)


@pin.route("/pin/create", methods=['GET', 'POST'])
@login_required
def create_new():
    """Creating new pin"""
    category_data = Category.query.all()
    form = PinCreation()
    if form.validate_on_submit():
        picture_file = save_picture(form.picture.data)
        #upload_result = cloudinary.uploader.upload(form.picture.data, folder="Pins")
        #print(f'------upload result---{upload_result}')

        pin = Pins(
            title=form.title.data,
            pin_content=form.pin_content.data,
            is_private=form.is_private.data,
            author=current_user,
            category_id=request.form.get("category"),
            image_file=picture_file
        )
        db.session.add(pin)
        db.session.commit()
        flash("New Pin is created", category='success')
        return redirect(url_for("pin.view_pins"))
    return render_template('create_pin.html', form=form, category_data=category_data, legend="Create New Pin")


@pin.route("/home")
@pin.route("/pin/views", methods=['GET'])
@login_required
def view_pins():
    """Showing all the pins"""
    page = request.args.get('page', 1, type=int)
    pins = Pins.query.filter_by(is_private=False).paginate(page=page, per_page=10)
    return render_template('view_pins.html', pins=pins)


@pin.route("/createdpin", methods=['GET'])
@login_required
def view_created_pins():
    """ user's created pins"""
    user = User.query.get(current_user.id)
    pins = user.pins
    return render_template('createdpins.html', pins=pins)


@pin.route("/createdpin/delete/<pin_id>", methods=['GET'])
@login_required
def delete_pins(pin_id):
    """Delete a pin"""
    pin = Pins.query.get_or_404(pin_id)
    db.session.delete(pin)
    db.session.commit()
    flash(' Your Pin has been deleted', category='success')
    return redirect(url_for('pin.view_created_pins'))


@pin.route("/createdpin/update/<pin_id>", methods=['GET', 'POST'])
@login_required
def update_pins(pin_id):
    """Update pin"""
    pin = Pins.query.get_or_404(pin_id)
    form = PinCreation()
    if form.validate_on_submit():
        pin.title = form.title.data
        pin.pin_content = form.pin_content.data
        pin.is_private = form.is_private.data
        db.session.commit()
        flash('Your Pin has been updated', 'success')
        return redirect(url_for('pin.view_created_pins'))
    elif request.method == 'GET':
        form.title.data = pin.title  # for filling values
        form.pin_content.data = pin.pin_content
        form.is_private.data = pin.is_private

    return render_template('update_pin.html', legend='Update Pin', form=form)


@pin.route("/board/create", methods=['GET', 'POST'])
@login_required
def create_pin_board():
    """Creating a  new pin board"""
    form = PinboardCreation()
    if form.validate_on_submit():
        pinboard = Pinboard(
            pin_board_name=form.pin_board_name.data,
            board_is_private=form.board_is_private.data,
            user_id=current_user.id
        )
        db.session.add(pinboard)
        db.session.commit()
        flash('Your Pinboard is created', 'success')
    return render_template('create_board.html', form=form)


@pin.route("/pin/save/<pin_id>", methods=['GET', 'POST'])
@login_required
def save_pin(pin_id):
    """For saving pins"""
    save = SavePin.query.filter_by(user_id=current_user.id, pin_id=pin_id).all()
    if not save:
        savepin = SavePin(
            user_id=current_user.id,
            pin_id=pin_id
        )
        db.session.add(savepin)
        db.session.commit()

    flash('Pin is saved', category='success')
    return redirect(url_for('pin.view_pins'))


@pin.route("/pin/unsave/<pin_id>", methods=['GET', 'POST'])
@login_required
def unsave_pin(pin_id):
    """ To remove pin from saved collection"""
    pin = SavePin.query.filter_by(pin_id=pin_id).all()
    for p in pin:
        db.session.delete(p)
    db.session.commit()
    flash('Pin removed from saved collection', category='success')
    return redirect(url_for('pin.view_pins'))


@pin.route("/savedpins", methods=['GET'])
@login_required
def view_saved_pins():
    """For viewing all the saved pins"""
    pins = db.session.query(Pins).join(SavePin).filter(SavePin.user_id == current_user.id)
    return render_template('savedpins.html', pins=pins)


@pin.route("/pin/<int:pin_id>", methods=['GET', 'POST'])
@login_required
def view_detailed_pin(pin_id):
    """ To view detailed pin"""
    alreadyliked = Vote.query.filter_by(user_id=current_user.id, pin_id=pin_id).all()
    if alreadyliked:
        likee = True
    else:
        likee = False
    form = AddPinToPinboard()
    commentform = CommentForm()
    pin = Pins.query.get_or_404(pin_id)
    boards = Pinboard.query.filter_by(user_id=current_user.id)
    if commentform.validate_on_submit():
        comment = Comments(
            user_id=current_user.id,
            pin_id=pin_id,
            comment=commentform.comment.data
        )
        db.session.add(comment)
        db.session.commit()
        flash('Comment is posted', category='success')
        return redirect(url_for('pin.view_detailed_pin', pin_id=pin_id))
    if form.validate_on_submit():
        flash("Pin added to your pinboard", category='success')
        board_id = request.form.get("category")
        return redirect(url_for('pin.add_to_pinboard', pin_id=pin_id, board_id=board_id))
    return render_template('pin.html', pin=pin, boards=boards, form=form, like=likee, commentform=commentform)


@pin.route("/pin/<int:pin_id>/<int:board_id>", methods=['GET', 'POST'])
@login_required
def add_to_pinboard(pin_id, board_id):
    """ To add a pin to already created pin-boards"""
    board_of_pins = Board_of_Pins(
        pin_id=pin_id,
        pinboard_id=board_id
    )
    db.session.add(board_of_pins)
    db.session.commit()
    return redirect(url_for('pin.view_detailed_pin', pin_id=pin_id))


@pin.route("/pinboard/view", methods=['GET', 'POST'])
@login_required
def view_pinboard():
    """To view pin-board"""
    pinboard = Pinboard.query.filter_by(user_id=current_user.id).all()
    return render_template('pinboard.html', pinboard=pinboard)


@pin.route("/pinboard/<board_id>", methods=['GET', 'POST'])
@login_required
def view_pins_in_board(board_id):
    """To view pins in board"""
    pins = db.session.query(Pins).join(Board_of_Pins).filter(Board_of_Pins.pinboard_id == board_id)
    return render_template('view_pins_in_pinboard.html', pins=pins, board_id=board_id)


@pin.route("/board/update/<board_id>", methods=['GET', 'POST'])
@login_required
def update_pinboard(board_id):
    """Update Pinboard"""
    pinboard = Pinboard.query.filter_by(id=board_id).first()
    form = PinboardCreation()
    if form.validate_on_submit():
        pinboard.pin_board_name = form.pin_board_name.data
        pinboard.board_is_private = form.board_is_private.data
        db.session.commit()
        flash('pinboard is updated', category='success')
        return redirect(url_for('pin.view_pinboard'))
    elif request.method == 'GET':
        form.pin_board_name.data = pinboard.pin_board_name
        form.board_is_private.data = pinboard.board_is_private
    return render_template('create_board.html', form=form)


@pin.route("/pin/remove/<board_id>/<pin_id>", methods=['GET', 'POST'])
@login_required
def remove_pin_from_board(board_id, pin_id):
    """Removing a pin from a board"""
    pin_in_board = Board_of_Pins.query.filter_by(pinboard_id=board_id, pin_id=pin_id).first()
    db.session.delete(pin_in_board)
    db.session.commit()
    flash('Pin has been removed from this pinboard', category='success')
    return redirect(url_for('pin.view_pins_in_board', board_id=board_id))


@pin.route("/pinboard/delete/<int:board_id>")
@login_required
def delete_pinboard(board_id):
    """For deleting entire board"""
    board = Pinboard.query.get_or_404(board_id)
    pin_in_board = Board_of_Pins.query.filter_by(pinboard_id=board_id).all()
    for board in pin_in_board:
        db.session.delete(board)
    db.session.delete(board)
    db.session.commit()
    flash('Pinboard is deleted', category='success')
    return redirect(url_for('pin.view_pinboard'))


@pin.route("/pins/filter", methods=['GET', 'POST'])
@login_required
def filter_pins_by_category():
    """Filter pins according to categories"""
    category_data = Category.query.all()
    form = FilteredPins()
    if form.validate_on_submit():
        return redirect(url_for('pin.view_filtered_pins', category_id=request.form.get("category")))
    return render_template('filter_pins.html', category_data=category_data, form=form)


@pin.route("/pins/filter/view/<category_id>")
@login_required
def view_filtered_pins(category_id):
    """Viewing pins according to various categories"""
    page = request.args.get('page', 1, type=int)
    pins = Pins.query.filter_by(category_id=category_id, is_private=False).paginate(page=page, per_page=10)
    return render_template('view_pins.html', pins=pins)


@pin.route("/pin/like/<pin_id>")
@login_required
def like(pin_id):
    """To Like a Pin"""
    alreadyliked = Vote.query.filter_by(user_id=current_user.id, pin_id=pin_id).all()
    if not alreadyliked:
        like = Vote(
            user_id=current_user.id,
            pin_id=pin_id
        )
        db.session.add(like)
        db.session.commit()

    return redirect(url_for('pin.view_detailed_pin', pin_id=pin_id))


@pin.route("/pin/unlike/<pin_id>")
@login_required
def unlike(pin_id):
    """ To Unlike a pin"""

pinterest/templates/admin.html
{% extends "layout.html" %}
{% block content %}
<div class="list-group">
  <a href="{{url_for('admin.view_user_info')}}" class="list-group-item list-group-item-action ">
    User Option
  </a>
  <a href="{{url_for('admin.category')}}" class="list-group-item list-group-item-action">Category Option</a>
  <a href="#" class="list-group-item list-group-item-action">Others</a>

</div>
{%endblock%}

pinterest/templates/comment.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{form.hidden_tag()}}
			<fieldset class="form-group">

					<div class="form-group">
						{{form.comment.label(class="form-control-label")}}
						{%if form.comment.errors%}
						{{form.comment(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.comment.errors%}
								<span>{{error}}</span>
							{%endfor%}
						</div>
						{%else%}
							{{form.comment(class="form-control form-control-lg ")}}
						{%endif%}
					</div>
			</fieldset>
			<div>
				{{form.submit(class="btn btn-outline-info")}}
			</div>
		</form>
	</div>
{% endblock %}

pinterest/templates/filter_pins.html
{% extends "layout.html" %}

{% block content %}
	<div class="content-section">

	  <!-- FORM HERE -->

	  	<form method="POST" action="" enctype="multipart/form-data">
	  		{{form.hidden_tag()}}
	  		<fieldset class="form-group">
	  			<legend class="border-bottom mb-4">{{legend}}</legend>

				<div class="form-group">
	  					<label for="category">
							Please select category
						</label>
					<select name="category"  id="category" >
						{% for category in category_data%}
						<option value="{{category.id}}">
							{{category.category_name}}
						</option>
						{%endfor%}
					</select>
	  				</div>


	  		</fieldset>
	  		<div class="form-group">
	  			{{form.submit(class="btn btn-outline-info")}}
	  		</div>
	  	</form>
	  </div>

{% endblock%}

pinterest/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for ('static',filename='main.css')}}">

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


	{%if title%}
		<title>Pinterest  -{{title}}</title>
	{%else%}
		<title>Pinterest </title>
	{%endif%}
</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
			<i class="fa fa-pinterest" style="font-size:37px;color:red"></i>
			{%if current_user.is_admin%}
	      <a class="navbar-brand mr-4" href="{{url_for('admin.home')}}">interest </a>

			{%else%}
			<a class="navbar-brand mr-4" href="{{url_for('pin.view_pins')}}">interest </a>
			{%endif%}
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>`
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
				{%if current_user.is_admin%}
				<a class="nav-item nav-link" href="{{url_for('admin.home')}}">Home</a>
				{%else%}
				<a class="nav-item nav-link" href="{{url_for('pin.view_pins')}}">Home</a>


				{%endif%}
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
    		  {% if current_user.is_authenticated %}
				<a class="nav-item nav-link" href="{{url_for('pin.create_new')}}">New Pin</a>
				<a class="nav-item nav-link" href="{{url_for('pin.filter_pins_by_category')}}">View Filtered Pins</a>



				<div class="dropdown show">
				  <a class="btn  dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					 Account
				  </a>

				  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
					<a class="dropdown-item" href="{{url_for('users.change_password')}}">Change Password</a>
					<a class="dropdown-item" href="{{url_for('users.account')}}">Update Profile</a>
					<a class="dropdown-item" href="{{url_for('pin.view_saved_pins')}}">Your saved pins</a>
					<a class="dropdown-item" href="{{url_for('pin.view_pinboard')}}">Your Pinboard</a>
					  <a class="dropdown-item" href="{{url_for('pin.create_pin_board')}}">Create Pinboard</a>
					<a class="dropdown-item" href="{{url_for('pin.view_created_pins')}}">Created Pins</a>
				  	<a class="dropdown-item" href="{{url_for('users.logout')}}">Logout</a>
				  </div>
				</div>


    		  {%else%}

		          <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
		          <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
	          {%endif%}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-12">
	    	{%with messages = get_flashed_messages(with_categories=true)%}
	    	{%if messages%}
	    		{%for category,message in messages%}
	    		<div class="alert alert-{{category}}">
	    			{{message}}
	    		</div>
	    		{%endfor%}
	    	{%endif%}
	    	{%endwith%}
	      {% block content %}{% endblock %}

	    </div>


	  </div>
	</main>


	<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

</body>
</html>

pinterest/templates/pin.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="card-img image article-img" src="/static/pin_pics/{{ pin.image_file }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{url_for('pin.profile',pin_id=pin.id)}}">{{ pin.author.username }}</a>

        <form method="POST" action="">
			{{form.hidden_tag()}}
			<fieldset class="form-group">



        <div class="form-group">
          <label for="category">
              Want to add in your pinboard??
          </label>
      <select name="category"  id="category" >
      {% for board in boards%}
          <option value="{{board.id}}">
            {{ board.pin_board_name }}
          </option>
      {% endfor %}
      </select>

      </div>
              <div>
				{{form.submit(class="btn btn-sm btn-outline-info")}}
			</div>
            </fieldset></form>
      {% if not like%}
      <a class="btn btn-primary" href="{{url_for('pin.like',pin_id=pin.id)}}" role="button">LIKE</a>

      {% else %}
      <a class="btn btn-primary" href="{{url_for('pin.unlike',pin_id=pin.id)}}" role="button">UNLIKE</a>
        {% endif %}
          <small><b>{{pin.likes.count()}}</b> like</small>
      </div>
      <h2 class="article-title">{{ pin.title }}</h2>
      <p class="article-content">{{ pin.pin_content }}</p>
     <form method="POST" action="">
			{{commentform.hidden_tag()}}
			<fieldset class="form-group">
				<h2>Comments</h2>
					<div class="form-group">
						{{commentform.comment.label(class="form-control-label")}}
						{%if commentform.comment.errors%}
						{{commentform.comment(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in commentform.comment.errors%}
								<span>{{error}}</span>
							{%endfor%}
						</div>
						{%else%}
							{{commentform.comment(class="form-control form-control-lg ")}}
						{%endif%}
					</div>
			</fieldset>
			<div>
				{{commentform.submit(class="btn btn-outline-info")}}
			</div>
		</form>
        <small><b>{{pin.comments.count() }}</b> comments</small>
      {% if pin.comments %}
                {% if pin.comments.count() > 0 %}



                    <p>
                    {% for comment in pin.comments %}
        <article class="media content-section">
  <img class="rounded-circle comment-img" src="{{  comment.user.image_file }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="#">{{ comment.user.username }}</a>
      <small class="text-muted">{{ comment.date_commented.strftime('%Y-%m-%d') }}</small>
        <p>{{ comment.comment }}</p>

    </div>

  </div>
</article>


                    {% endfor %}
                    </p>
                {% endif %}
                {% endif %}
    </div>
  </article>
  <!-- Modal -->

{% endblock content %}

pinterest/templates/profile.html
{% extends "layout.html" %}

{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{image_file}}">
	    <div class="media-body">
	      <h2 class="account-heading">{{user.username}}</h2>
	      <p class="text-secondary">{{user.email}}</p>
			{% if user != current_user %}
                <p>
                    <a href="{{ url_for('chat.chat_func', recipient=user.username) }}">
                        {{('Send private message')}}
                    </a>
                </p>
                {% endif %}
	    </div>
	  </div>

		<a href="{{ url_for('pin.display_profile_pinboard',user=user.id)}}" class="btn btn-primary">Pinboards</a>
		<a href="{{ url_for('pin.profile_created_pins',user=user.id)}}" class="btn btn-primary">Created Pins</a>

{% endblock %}

pinterest/templates/savedpins.html
{% extends "layout.html" %}

{% block content %}

<section class="mt-4 mb-5">

    <div class="container-fluid mb-5">
        <div class="row">
            <div class="card-columns">
                {% for pin in  pins%}

                <div class="card card-pin">
                    <div class="image-container">
                        <img class="card-img image" src="/static/pin_pics/{{pin.image_file}}" alt="{{pin.title}}" >




                    </div>

                    <div class="card-body">
                        <a class="card-link" href="{{url_for('pin.view_detailed_pin',pin_id=pin.id)}}"><h5 class="card-title title">{{ pin.title }}</h5></a>
                        <a class="btn btn-primary" href="{{url_for('pin.unsave_pin',pin_id=pin.id)}}" role="button">UnSave</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>


{% endblock %}

pinterest/templates/view_pins.html
{% extends "layout.html" %}

{% block content %}

<section class="mt-4 mb-10">

    <div class="container mb-10">
        <div class="row">
            <div class="col-md-12">
                <div class="card-columns">

                        {% for pin in pins.items%}
                        <div class="card card-pin">
                            <div class="image-container">
                                <a  href="{{url_for('pin.view_detailed_pin',pin_id=pin.id)}}"><img class="card-img image" src="/static/pin_pics/{{pin.image_file}}" alt="{{pin.title}}"></a>
                                <div class="overlay1">
                                    <a class="btn image-save btn-success" href="{{ url_for('pin.save_pin',pin_id=pin.id)}}" role="button">Save</a>
                                </div>
                            </div>
                            <div class="card-body">
                                <a class="card-link" href="{{url_for('pin.view_detailed_pin',pin_id=pin.id)}}"><h5 class="card-title title">{{ pin.title }}</h5></a>
                            </div>
                        </div>
                        {% endfor %}


                </div>

            </div>
        </div>
    </div>
</section>
{% for page_num in pins.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if pins.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('pin.view_pins', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('pin.view_pins', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}

{% endblock %}